### PR TITLE
Fix compatibility with Libertine font package

### LINKED ISSUE #4: Font-related error when using Libertine
When using fvextra (via minted) with the [Libertine font package](https://www.ctan.org/pkg/libertine), I get the following error message:

    /usr/local/texlive/2016/texmf-dist/tex/latex/fvextra/fvextra.sty:562: Undefined control sequence \mdseries@tt.
    /usr/local/texlive/2016/texmf-dist/tex/latex/fvextra/fvextra.sty:562: leading text: ...FV@BreakSymbolIndentLeft}{\ttfamily xxxx}

The Libertine fonts depend on the mweights package for font configuration, but mweights uses the `\AtBeginDocument` command to delay some parts of the font setup.

It seems that the `\settowidth` command on line 562 is failing because the font configuration is not complete at the time that fvextra tries to compute these widths.

The following LaTeX document can be used to reproduce the error:

    \documentclass{article}
    \usepackage[T1]{fontenc}
    \usepackage{libertine}
    \usepackage{minted}
    \begin{document}
    \begin{minted}{c}
        int main(int argc, char *argv[]) {
            return 0;
        }
    \end{minted}
    \end{document}

### PR DESCRIPTION
**Pull request by DaoWen**
Delay \settowidth (which depends font settings) using \AtBeginDocument.

Closes #4.

### CODE REVIEW

**Comment by gpoore** [comment]
Thanks for this! I need to check to see if there are any similar font issues that I need to fix along with this, and then I'll merge.

**Comment by DaoWen** [comment]
I love using your minted package to format all of my code listings, so I am glad to contribute back in some small way.

This patch is so trivial that I don't think it would even be possible to make a copyright claim, but just for the record: I assign the copyright of the code in this patch to Geoffrey M. Poore.

**Comment by eg9** [comment]
I'd do it a bit differently: a font support package might delay code at begin document, so the order loading with `fvextra` might become important. My suggestion is to use `\AfterEndPreamble`

    \newdimen\FV@BreakSymbolIndentLeft
    \define@key{FV}{breaksymbolindentleft}{\FV@BreakSymbolIndentLeft=#1\relax}
    \define@key{FV}{breaksymbolindent}{\fvset{breaksymbolindentleft=#1}}
    \newdimen\FV@BreakSymbolIndentRight
    \define@key{FV}{breaksymbolindentright}{\FV@BreakSymbolIndentRight=#1\relax}
    \AfterEndPreamble{%
      \settowidth{\FV@BreakSymbolIndentLeft}{\ttfamily xxxx}%
      \settowidth{\FV@BreakSymbolIndentRight}{\ttfamily xxxx}%
    }

so this code will be executed after anything done `\AtBeginDocument`.

**Comment by gpoore** [comment]
@eg9 That's a good point. At the moment, I'm thinking about doing a test for the existence of `\mdseries@tt` when `fvextra` is loaded, and if it exists, setting the indent. That way saved boxes could work immediately. Then there would be a second check `\AfterEndPreamble`. Although that could result in a situation in which a saved box from the preamble isn't consistent with later text due to font changes, so it might be better to have `\FV@BreakSymbolIndentLeft` and `\FV@BreakSymbolIndentRight` give an error message if used in the preamble.

Another, possibly better, option would be to add an indentation setting that is just a particular number of characters, and always calculate the actual width of this on the fly right before use. That way, indentation would stay consistent in terms of number of characters regardless of font changes.

**Comment by DaoWen** [comment]
@gpoore I think I like your second option better. Since the width is font-dependent, delaying the width calculation until you're actually using it will ensure that the width stays consistent with the current font.

**Comment by gpoore** [comment]
@DaoWen I'm closing this because the issue is fixed in v1.3. The new version allows indentation to be specified as a particular number of characters. The width of the characters is calculated immediately before use, so this approach automatically adjusts even if fonts and font sizes are changed, and there are no longer any calculations in the preamble to cause problems.

**Pull request closed without merging**
